### ISSUE TITLE
Don't send action when button is disabled

### ISSUE THREAD

**Issue by sly7-7** [deanylev/ember-ladda-button#7]
Hi, thank you for this wrapper around Ladda 👍 

What do you think of checking the disable state of the button before sending this action ? 
Well, maybe I'm just making a mistake somewhere, but it seems like I can for example click on the button whereas the action is already processed.

**Comment by deanylev** [comment]
Hmm you shouldn't be able to click the button while the request is in flight, though I'm happy to add an extra check just in case

**Comment by sly7-7** [comment]
@deanylev Thank you for the feedback. I have to refresh my ideas about this ^^. I'm on holidays until next monday (02/15), I will come back with a PR during the next week.

**Comment by sly7-7** [comment]
@deanylev I hope this is good. I don't know what's your plan with this addon, but I think this may be a good idea to migrate it to glimmer + (maybe) ember-concurrency to handle the asynchrony (maybe overkill though ?)
